### ISSUE TITLE
The template project should drop Blueprint CSS

### ISSUE THREAD

**Issue by heharkon** [lift/basic-app.g8#4]
While this g8 template excellently shows the ropes to using Lift, I think, from "onboarding experience" point of view, the usage of abandoned Blueprint CSS project (at least that version) looks a bit bad and sad in the eyes of the newcomers. The visual appeal should provice a bit more bang and also the current CSS seems to be non-responsive etc.

We could use FoBo of course, but perhaps if module dependancy is to be avoided here, some simple yet popular CSS framework might do the trick. Like single file CSS or even classless one.  I'm looking into alternative currently.

Probably the Blueprint CSS could be pruned from the framework side (webkit) then as well?

**Comment by farmdawgnation** [comment]
I’m inclined to say we should just include the latest Bootstrap without FoBo. Folks could always add it in if they want it later, but it’ll be easier to keep up to date with fewer dependencies or customizations.

I’d even say let’s use the built in classes from Bootstrap for layout as much as it makes my eye twitch a bit. 😂

**Comment by heharkon** [comment]
#5 Added first PR towards better looking template app.
